/**
 * AUTO-GENERATED by scripts/build-knowledge.mjs — do not edit by hand.
 * Source: src/data/knowledge/*.md
 * Regenerate with: npm run knowledge
 */

export interface KnowledgeSource {
  url: string
  title: string
}

export interface KnowledgeEntry {
  /** Present for satellite-specific entries. */
  noradId?: number
  /** Present for topic-level entries (kebab-case). */
  topic?: string
  name: string
  aliases: string[]
  sources: KnowledgeSource[]
  body: string
}

export const KNOWLEDGE: KnowledgeEntry[] = [
  {
    "name": "Aqua",
    "aliases": [
      "EOS PM-1"
    ],
    "sources": [
      {
        "url": "https://aqua.nasa.gov/",
        "title": "NASA — Aqua Mission"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Aqua_(satellite)",
        "title": "Wikipedia — Aqua (satellite)"
      },
      {
        "url": "https://www.earthdata.nasa.gov/sensors/aqua",
        "title": "NASA Earthdata — Aqua"
      }
    ],
    "body": "Aqua is a NASA Earth-observation satellite in a sun-synchronous orbit at\napproximately 705 km altitude and 98.2° inclination. It launched from\nVandenberg Air Force Base on 4 May 2002 as the second flagship mission of the\nEarth Observing System (EOS), following Terra. Its original design life was\nsix years; it has now been returning data for over two decades.\n\nAqua carries six instruments — AIRS, AMSU-A, HSB (failed 2003), CERES, MODIS,\nand AMSR-E (retired 2011) — that together measure Earth's water cycle,\ncloud cover, sea-surface temperatures, aerosols, and radiation budget. Its\nMODIS imagery in particular is central to daily global monitoring of\nvegetation, wildfires, and ocean chlorophyll.\n\nAqua flew in the \"A-Train\" formation with several other afternoon sun-sync\nsatellites until a 2022 exit manoeuvre placed it in a lower drift orbit\nahead of end-of-mission. NASA declared the mission ended in its prime\nEarth-science capacity in 2024 and continues to monitor its passive decay\nwhile selected instruments provide reduced data.\n\nAqua's long baseline of cross-calibrated observations has been foundational to\nclimate-trend analyses and weather forecasting worldwide.",
    "noradId": 27424
  },
  {
    "name": "Chandra X-ray Observatory",
    "aliases": [
      "Chandra",
      "CXO",
      "AXAF"
    ],
    "sources": [
      {
        "url": "https://chandra.harvard.edu/",
        "title": "Chandra X-ray Observatory (SAO / NASA)"
      },
      {
        "url": "https://science.nasa.gov/mission/chandra/",
        "title": "NASA — Chandra"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Chandra_X-ray_Observatory",
        "title": "Wikipedia — Chandra X-ray Observatory"
      }
    ],
    "body": "The Chandra X-ray Observatory is one of NASA's four Great Observatories,\nalongside Hubble, Spitzer, and Compton. It launched on STS-93 aboard Space\nShuttle Columbia on 23 July 1999 and was boosted into an unusual highly\nelliptical 64-hour orbit that carries it from ~14,000 km out to ~134,000 km —\nwell above Earth's radiation belts and providing long uninterrupted\nobservations per orbit.\n\nChandra's high-resolution X-ray mirrors (designed by the Smithsonian\nAstrophysical Observatory and built by Hughes Danbury) give it sub-arcsecond\nangular resolution — about 25× sharper than previous X-ray observatories.\nIts instruments, including the Advanced CCD Imaging Spectrometer (ACIS) and\nHigh Resolution Camera (HRC), have produced landmark images of supernova\nremnants, active galactic nuclei, galaxy clusters, and black-hole accretion.\n\nOriginally planned for a five-year mission, Chandra passed its 25th\nanniversary in 2024. Its thermal insulation has degraded over time, limiting\nallowable pointing orientations, but the observatory continues to produce\nscience despite ongoing budget debates within NASA about funding levels.\n\nChandra's key scientific contributions include direct imaging of matter\nfalling into Sgr A* (the Milky Way's central black hole), observations of\nthe Bullet Cluster that helped constrain dark matter models, and ongoing\nmonitoring of supernova remnants and neutron stars.",
    "noradId": 25867
  },
  {
    "name": "GOES-16",
    "aliases": [
      "GOES-R",
      "GOES 16",
      "GOES East"
    ],
    "sources": [
      {
        "url": "https://www.nesdis.noaa.gov/current-satellite-missions/currently-flying/goes-r-series",
        "title": "NOAA NESDIS — GOES-R Series"
      },
      {
        "url": "https://www.goes-r.gov/",
        "title": "NOAA — GOES-R Program"
      },
      {
        "url": "https://en.wikipedia.org/wiki/GOES-16",
        "title": "Wikipedia — GOES-16"
      }
    ],
    "body": "GOES-16 (originally GOES-R) is a NOAA geostationary weather satellite, the\nfirst of the GOES-R series. It launched on 19 November 2016 aboard an Atlas V\nfrom Cape Canaveral and operated as \"GOES East\" at 75.2° W longitude from\nDecember 2017, replacing GOES-13. In early 2025 GOES-19 was commissioned\nas the operational GOES East, and GOES-16 was moved to an on-orbit standby\nposition.\n\nAt geostationary altitude (~35,786 km over the equator), GOES-16 keeps pace\nwith Earth's rotation and stares continuously at the Americas and adjacent\nocean basins. Its Advanced Baseline Imager (ABI) produces full-disk imagery\nevery 10 minutes in 16 spectral bands, and its Geostationary Lightning\nMapper (GLM) provides the first operational continuous lightning detection\nfrom GEO.\n\nGOES-16 data is a backbone of U.S. hurricane, severe-weather, and\naviation-weather forecasting. Its five-minute mesoscale sectors are widely\nused during rapidly developing convective events, and its space-environment\ninstruments feed NOAA's Space Weather Prediction Center.\n\nDesigned for ~15 years of service, GOES-16 is expected to remain an active\non-orbit spare through the end of the decade.",
    "noradId": 41866
  },
  {
    "name": "GPS IIF-9",
    "aliases": [
      "GPS BIIF-9",
      "USA-258",
      "Navstar 72"
    ],
    "sources": [
      {
        "url": "https://www.gps.gov/systems/gps/space/",
        "title": "GPS.gov — Space Segment"
      },
      {
        "url": "https://en.wikipedia.org/wiki/GPS_Block_IIF",
        "title": "Wikipedia — GPS Block IIF"
      },
      {
        "url": "https://www.spaceforce.mil/",
        "title": "U.S. Space Force"
      }
    ],
    "body": "GPS IIF-9 (Navstar 72, USA-258) is a U.S. Air Force (now Space Force) GPS\nBlock IIF navigation satellite launched on 2 August 2014 aboard an Atlas V\nfrom Cape Canaveral. It operates in a medium Earth orbit at roughly 20,200 km\naltitude with a 55° inclination in one of six orbital planes — the standard\nGPS constellation geometry that guarantees global four-satellite coverage.\n\nBlock IIF satellites were the twelfth generation of GPS spacecraft. They\nadded a new civil L5 signal (for aviation safety-of-life use), improved\natomic clock accuracy via rubidium standards, and offered a longer 12-year\ndesign life than earlier blocks. Twelve IIF vehicles were launched between\n2010 and 2016.\n\nLike every GPS satellite, GPS IIF-9 continuously broadcasts precise timing\nand ephemeris data. Receivers on the ground combine signals from four or\nmore visible satellites to compute position, velocity, and time — the\nfoundation of almost all modern civilian positioning, navigation, and\ntiming infrastructure. The GPS constellation is complemented by other\nGNSS systems: Europe's Galileo, Russia's GLONASS, and China's BeiDou.\n\nGPS IIF-9 remains operational as of 2025, alongside the growing GPS III\nseries (launched from 2018 onward) that are gradually replacing the older\nBlock IIR and IIF vehicles.",
    "noradId": 40105
  },
  {
    "name": "Hitomi",
    "aliases": [
      "ASTRO-H",
      "Hitomi (ASTRO-H)"
    ],
    "sources": [
      {
        "url": "https://global.jaxa.jp/projects/sas/astro_h/",
        "title": "JAXA — ASTRO-H / Hitomi"
      },
      {
        "url": "https://heasarc.gsfc.nasa.gov/docs/hitomi/",
        "title": "NASA HEASARC — Hitomi"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Hitomi_(satellite)",
        "title": "Wikipedia — Hitomi (satellite)"
      }
    ],
    "body": "Hitomi (originally ASTRO-H) was a Japanese X-ray astronomy satellite built by\nJAXA with contributions from NASA, ESA, CSA, and several universities. It\nlaunched on 17 February 2016 on an H-IIA rocket from Tanegashima and was\nrenamed Hitomi (\"pupil of the eye\") after reaching orbit.\n\nHitomi carried four co-aligned instruments, including the groundbreaking Soft\nX-ray Spectrometer (SXS) — a cryogenically cooled microcalorimeter array\ncapable of spectral resolution previously unachievable in the X-ray band.\nDuring its brief commissioning, SXS delivered a landmark measurement of gas\nmotions in the Perseus galaxy cluster, demonstrating the potential of\ncalorimeter spectroscopy.\n\nOn 26 March 2016, a chain of attitude-control failures caused Hitomi to\nenter an uncontrolled spin and break apart. JAXA declared the mission lost\non 28 April 2016 after ~38 days in orbit. The debris remained catalogued\nunder NORAD 41337 as it slowly re-entered over subsequent years.\n\nHitomi's scientific legacy lives on through the follow-on mission XRISM\n(X-Ray Imaging and Spectroscopy Mission), launched September 2023, which\nre-flew a calorimeter-based instrument derived from Hitomi's SXS design.",
    "noradId": 41337
  },
  {
    "name": "Hubble Space Telescope",
    "aliases": [
      "Hubble",
      "HST"
    ],
    "sources": [
      {
        "url": "https://hubblesite.org/",
        "title": "HubbleSite (NASA / STScI)"
      },
      {
        "url": "https://science.nasa.gov/mission/hubble/",
        "title": "NASA — Hubble Space Telescope"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Hubble_Space_Telescope",
        "title": "Wikipedia — Hubble Space Telescope"
      }
    ],
    "body": "The Hubble Space Telescope is a 2.4-metre optical/UV/NIR observatory jointly\noperated by NASA and ESA. It launched on STS-31 aboard Space Shuttle Discovery\non 24 April 1990 and orbits at roughly 540 km altitude with a 28.5° inclination.\n\nHubble's early spherical aberration was corrected by astronauts during Servicing\nMission 1 (STS-61, December 1993), and four subsequent shuttle servicing\nmissions upgraded instruments and reaction wheels, most recently SM4 in May\n2009. No further crewed servicing is possible now that the Shuttle is retired.\n\nHubble has produced some of the most scientifically and culturally important\nastronomical images of the modern era — the Deep Fields, the Pillars of\nCreation, and direct observations of exoplanet atmospheres among them. Its\nobservations have been cited in tens of thousands of peer-reviewed papers.\n\nThe telescope continues to operate in a degraded-but-functional mode as of\n2025. Its orbit is slowly decaying; without a reboost it is expected to\nre-enter the atmosphere some time in the mid-to-late 2030s. NASA and private\npartners have studied reboost missions but none is currently funded.",
    "noradId": 20580
  },
  {
    "name": "International Space Station",
    "aliases": [
      "ISS",
      "Zarya",
      "ISS (ZARYA)"
    ],
    "sources": [
      {
        "url": "https://www.nasa.gov/international-space-station/",
        "title": "NASA — International Space Station"
      },
      {
        "url": "https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/International_Space_Station",
        "title": "ESA — International Space Station"
      },
      {
        "url": "https://en.wikipedia.org/wiki/International_Space_Station",
        "title": "Wikipedia — International Space Station"
      }
    ],
    "body": "The International Space Station (ISS) is a large modular space station in low\nEarth orbit, operated since 1998 by a partnership between NASA, Roscosmos,\nESA, JAXA, and CSA. The first module, Zarya, launched on 20 November 1998;\nthe station has been continuously crewed since Expedition 1 arrived on\n2 November 2000.\n\nIt orbits at roughly 400 km mean altitude with an inclination of ~51.6°,\ncompleting one lap every ~92 minutes and crossing most of the inhabited world\nbetween latitudes ±51.6°. Crews of typically six to seven astronauts rotate\nthrough six-month increments, conducting research in microgravity across\nbiology, materials science, fundamental physics, and Earth observation.\n\nPropulsive reboosts — from visiting Progress, Cygnus, or Zvezda itself —\ncounter atmospheric drag and keep the station from decaying. Current NASA/ISS\npartner plans have ISS operating through at least 2030, with a planned\ncontrolled deorbit thereafter using a dedicated deorbit vehicle under\ndevelopment by SpaceX.\n\nAs of 2025, the ISS remains the largest crewed object in orbit, massing over\n420 tonnes with a habitable volume roughly equivalent to a Boeing 747 interior.",
    "noradId": 25544
  },
  {
    "name": "James Webb Space Telescope",
    "aliases": [
      "JWST",
      "Webb",
      "James Webb"
    ],
    "sources": [
      {
        "url": "https://science.nasa.gov/mission/webb/",
        "title": "NASA — James Webb Space Telescope"
      },
      {
        "url": "https://www.esa.int/Science_Exploration/Space_Science/Webb",
        "title": "ESA — Webb"
      },
      {
        "url": "https://en.wikipedia.org/wiki/James_Webb_Space_Telescope",
        "title": "Wikipedia — James Webb Space Telescope"
      }
    ],
    "body": "The James Webb Space Telescope (JWST) is a 6.5-metre segmented infrared\nobservatory operated by NASA in partnership with ESA and CSA. It launched on\nan Ariane 5 from Kourou on 25 December 2021 and completed a month-long\ncruise, sunshield deployment, and mirror unfurl before arriving at the\nSun–Earth L2 Lagrange point in January 2022.\n\nWebb does not orbit Earth: it orbits L2 in a halo orbit roughly 1.5 million km\nsunward-facing-away from Earth. That means its NORAD catalog entry (50463)\nexists but is not useful for live SGP4 propagation — standard tracking tools\ncannot compute a meaningful altitude or ground track for it. The mission\ncarries enough propellant for science operations well past 2040 thanks to an\nunusually efficient launch insertion.\n\nJWST's four instruments (NIRCam, NIRSpec, MIRI, NIRISS/FGS) probe the earliest\ngalaxies in the universe, the atmospheres of exoplanets, star-forming regions,\nand objects in our own solar system. By 2025 it had already reshaped\nunderstanding of early-universe galaxy formation and provided the first direct\nmid-infrared detections of CO₂ in exoplanet atmospheres.\n\nBecause it lives at L2, JWST observes nearly the full sky over the course of\na year but cannot be serviced by humans — it is too far away.",
    "noradId": 50463
  },
  {
    "name": "Starlink-1007",
    "aliases": [
      "STARLINK-1007",
      "Starlink v1.0 L1"
    ],
    "sources": [
      {
        "url": "https://www.starlink.com/",
        "title": "Starlink (official)"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Starlink",
        "title": "Wikipedia — Starlink"
      },
      {
        "url": "https://www.spacex.com/launches/",
        "title": "SpaceX Launches"
      }
    ],
    "body": "Starlink-1007 (NORAD 44713) is one of sixty v1.0 satellites launched on the\n\"Starlink v1.0 L1\" mission — the first fully operational Starlink batch —\non 11 November 2019 from Cape Canaveral SLC-40 aboard a Falcon 9. It is\nrepresentative of the early operational Starlink shell, orbiting near 550 km\naltitude at 53° inclination.\n\nEach v1.0 satellite masses ~260 kg, uses krypton-fuelled Hall-effect\nthrusters for station-keeping and deorbit, and carries phased-array antennas\nfor Ku-band user links plus Ka-band gateway links. Unlike later v1.5 and v2\nMini designs, v1.0 satellites do not carry laser inter-satellite links.\n\nSpaceX's Starlink constellation has grown from this first batch to well over\n6,000 active satellites serving millions of customers worldwide, with\ncontinued launches of v1.5 and v2 Mini vehicles on Falcon 9 and v2 full\nvehicles planned for Starship. Older v1.0 satellites are being gradually\ndeorbited — their propellant and attitude control gear wear out, and the\nnetwork is designed for rapid refresh.\n\nStarlink satellites have driven significant discussion in the astronomy\ncommunity about orbital brightness, radio-frequency interference, and the\nscale of megaconstellations.",
    "noradId": 44713
  },
  {
    "name": "Tiangong Space Station",
    "aliases": [
      "Tiangong",
      "Tianhe",
      "CSS",
      "Chinese Space Station"
    ],
    "sources": [
      {
        "url": "https://en.cmse.gov.cn/",
        "title": "China Manned Space Agency"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Tiangong_space_station",
        "title": "Wikipedia — Tiangong Space Station"
      },
      {
        "url": "https://www.nasaspaceflight.com/tag/tiangong/",
        "title": "NASASpaceflight — Tiangong coverage"
      }
    ],
    "body": "Tiangong (\"Heavenly Palace\") is China's third-generation crewed space station,\noperated by the China Manned Space Agency (CMSA). The core module Tianhe\nlaunched on 29 April 2021 on a Long March 5B from Wenchang; NORAD catalog\nnumber 48274 tracks this core module, which anchors the rest of the station.\n\nTwo laboratory modules — Wentian (July 2022) and Mengtian (October 2022) —\njoined Tianhe to complete the baseline T-shaped configuration. Tiangong\norbits at roughly 380–450 km altitude and 41.5° inclination, substantially\nlower in latitude than the ISS. The station is normally occupied by\nthree-person Shenzhou crews rotating on roughly six-month increments.\n\nTiangong supports microgravity science across biology, fluid physics, fundamental\nphysics, and life-support research, plus Earth observation using a deployable\nco-orbiting telescope module (Xuntian) scheduled to join later in the\ndecade. A fourth module expansion to a cross-shape is planned.\n\nChina has opened Tiangong to limited international collaboration through UN\nOffice for Outer Space Affairs partnerships, and has signalled that\nTiangong may be the only crewed orbital outpost after ISS retires.",
    "noradId": 48274
  },
  {
    "name": "Satellite Constellation",
    "aliases": [
      "constellation",
      "megaconstellation",
      "satellite constellation"
    ],
    "sources": [
      {
        "url": "https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits",
        "title": "ESA — Types of Orbits"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Satellite_constellation",
        "title": "Wikipedia — Satellite constellation"
      }
    ],
    "body": "A satellite constellation is a coordinated group of satellites working\ntogether as a system, typically spread across multiple orbital planes to\nachieve continuous coverage of Earth or a particular region. Unlike a\nsolitary satellite that only sees each ground point intermittently, a\nconstellation is designed so that at any moment — from any location it\ntargets — at least one (often several) satellites are overhead.\n\nClassic examples include the global navigation systems (GPS, Galileo, GLONASS,\nBeiDou), each using roughly 24–30 satellites in medium Earth orbit arranged\nin multiple planes to guarantee at least four satellites are visible anywhere\non Earth for positioning. The Iridium constellation of 66 LEO satellites\nprovides global phone coverage by handing off calls between neighbours.\n\nModern \"megaconstellations\" — Starlink, OneWeb, Project Kuiper, Guowang —\ndramatically scale this idea. Starlink alone fields thousands of LEO\nsatellites arranged in multiple shells at different altitudes and\ninclinations. They deliver low-latency broadband by passing user traffic\nbetween many satellites and ground gateways, often using optical\ninter-satellite links.\n\nDesigning a constellation involves trade-offs between number of satellites,\naltitude, inclination, phasing within and between planes, and tolerance to\nfailures. Walker-delta patterns are a common analytic framework for\nchoosing those parameters.",
    "topic": "constellation"
  },
  {
    "name": "Geostationary Orbit",
    "aliases": [
      "GEO",
      "geostationary",
      "geosynchronous",
      "geosynchronous orbit"
    ],
    "sources": [
      {
        "url": "https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits",
        "title": "ESA — Types of Orbits"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Geostationary_orbit",
        "title": "Wikipedia — Geostationary orbit"
      }
    ],
    "body": "A geostationary orbit (GEO) is a circular, equatorial orbit at an altitude\nof approximately 35,786 km (42,164 km radius from Earth's centre) where a\nsatellite's orbital period exactly matches Earth's rotation — one sidereal\nday, 23 h 56 min 4 s. A satellite there appears fixed over a single point\non the equator, which is what makes it the workhorse orbit for telecoms,\ntelevision, and geostationary weather satellites.\n\n\"Geosynchronous\" and \"geostationary\" are often used interchangeably but they\nare not identical. Geosynchronous means any orbit whose period matches Earth's\nrotation, including inclined or eccentric ones that trace a figure-8 or loop\nover a fixed longitude. Geostationary is the special case where the orbit\nis circular and equatorial (0° inclination), so the satellite truly stands\nstill in the sky.\n\nThe GEO ring is a scarce international resource, coordinated by the ITU.\nEach active satellite is assigned a nominal longitude slot (typically 2°\napart) and is station-kept with regular burns to counter the gravitational\ntugs of the Sun, Moon, and Earth's non-spherical mass distribution.\n\nDrawbacks of GEO include high insertion delta-v (a geostationary transfer\norbit is standard), a round-trip signal delay of ~240 ms, and the fact that\nvery high latitudes cannot see the satellite at all. These trade-offs are\nwhy low-Earth-orbit constellations (Starlink, OneWeb, Iridium) dominate the\nnewer telecommunications market.",
    "topic": "geostationary-orbit"
  },
  {
    "name": "Low Earth Orbit",
    "aliases": [
      "LEO",
      "low-earth orbit"
    ],
    "sources": [
      {
        "url": "https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits",
        "title": "ESA — Types of Orbits"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Low_Earth_orbit",
        "title": "Wikipedia — Low Earth orbit"
      }
    ],
    "body": "Low Earth Orbit (LEO) is the region of space below roughly 2,000 km altitude,\nthough most operational LEO satellites fly between about 300 km and 1,200 km.\nOrbital periods in LEO range from ~88 minutes at the low end to ~120 minutes\nat the upper bound; the ISS at ~400 km completes a lap every ~92 minutes.\n\nLEO hosts the vast majority of active satellites: Earth-observation platforms,\nweather sats, the ISS and Tiangong crewed stations, CubeSats, the Starlink\nand OneWeb broadband constellations, and most science missions. It is\npreferred because launch to LEO requires far less delta-v than higher orbits,\nsignal latency is low (~5–20 ms one way), and imaging resolution is much\nbetter than from GEO for equivalent optics.\n\nThe drawbacks are short pass durations (a given LEO satellite is over a\nsingle ground station for only minutes at a time), limited coverage footprint\nper satellite (requiring large constellations for continuous service), and\nnon-trivial atmospheric drag below ~600 km — satellites there require either\nstation-keeping thrusters or will decay within months to a few years.\n\nThe lower reaches of LEO are also increasingly crowded, driving conjunction\nanalyses, debris-avoidance manoeuvres, and international discussion of\nsustainable orbital-use practices.",
    "topic": "low-earth-orbit"
  },
  {
    "name": "Orbital Decay",
    "aliases": [
      "orbital decay",
      "atmospheric drag",
      "re-entry"
    ],
    "sources": [
      {
        "url": "https://www.nasa.gov/orbital-debris/",
        "title": "NASA — Orbital Debris Program"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Orbital_decay",
        "title": "Wikipedia — Orbital decay"
      },
      {
        "url": "https://www.esa.int/Space_Safety/Space_Debris",
        "title": "ESA — Space Debris"
      }
    ],
    "body": "Orbital decay is the gradual loss of altitude a satellite experiences as it\nloses orbital energy to drag from Earth's upper atmosphere. Although space\nis nominally \"vacuum,\" the atmosphere's exponentially thinning tail extends\nfar beyond the Kármán line (100 km), and any satellite below roughly 600 km\nis in measurable drag. Below ~300 km, decay becomes rapid — a dead satellite\nat that altitude may re-enter within weeks to a few months.\n\nThe decay rate depends on the satellite's ballistic coefficient\n(mass / drag-area), its altitude, and the density of the upper atmosphere at\nthat altitude. Atmospheric density itself varies by more than an order of\nmagnitude with solar activity: during solar maximum the upper atmosphere\nheats and expands, dramatically increasing drag on LEO spacecraft. SpaceX\nfamously lost 38 Starlink satellites launched in February 2022 to a\ngeomagnetic storm that inflated the atmosphere after their deployment.\n\nActive satellites counter decay with propulsive reboosts — the ISS regularly\nreceives boosts from visiting Progress/Cygnus vehicles or its own Zvezda\nthrusters. Once propellant is exhausted or a spacecraft fails, it eventually\nre-enters and burns up. Modern debris-mitigation guidelines call for LEO\nsatellites to deorbit within 25 years (or shorter, per recent FCC rules) of\nend-of-mission, either passively through drag or by active deorbit burn.\n\nMost re-entering satellites burn up completely; larger structures (like ISS\nmodules or rocket upper stages) can survive re-entry partially, which is\nwhy controlled deorbits target uninhabited ocean regions such as the South\nPacific \"spacecraft cemetery\" near Point Nemo.",
    "topic": "orbital-decay"
  },
  {
    "name": "Sun-Synchronous Orbit",
    "aliases": [
      "SSO",
      "sun-synchronous",
      "helio-synchronous"
    ],
    "sources": [
      {
        "url": "https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits",
        "title": "ESA — Types of Orbits"
      },
      {
        "url": "https://en.wikipedia.org/wiki/Sun-synchronous_orbit",
        "title": "Wikipedia — Sun-synchronous orbit"
      }
    ],
    "body": "A sun-synchronous orbit (SSO) is a near-polar low Earth orbit tuned so that\nthe satellite passes over any given point on Earth at roughly the same local\nsolar time every day. It achieves this by exploiting the J2 oblateness of\nEarth: a carefully chosen inclination (typically around 97–99°) causes the\norbit's ascending node to precess eastward at exactly the rate the Sun\nappears to drift across the sky — about 0.9856° per day.\n\nThe primary benefit is consistent lighting conditions. For Earth-observing\nmissions — weather satellites (Terra, Aqua, Suomi NPP, JPSS), imaging\nreconnaissance, land-use monitoring — this means every image of the same\nlocation is acquired under the same sun angle, making change detection and\nquantitative comparisons much easier.\n\nSSOs are typically at altitudes of 600–900 km with inclinations slightly\ngreater than 90°. The \"mean local time at the ascending node\" (MLTAN) is a\ndefining parameter; common choices are ~10:30 AM (morning orbit) or\n~1:30 PM (afternoon orbit) to maximise solar illumination without harsh\nshadows.\n\nBecause the precession depends on specific altitude–inclination pairings,\nSSO injections require more precision than ordinary orbits. Small drifts\naccumulate over time and require propulsive corrections, or the satellite's\nlocal time slowly wanders.",
    "topic": "sun-synchronous-orbit"
  }
]

const NORAD_INDEX: Map<number, KnowledgeEntry> = new Map(
  KNOWLEDGE.filter((e): e is KnowledgeEntry & { noradId: number } => e.noradId != null).map(
    (e) => [e.noradId, e],
  ),
)

const TOPIC_INDEX: Map<string, KnowledgeEntry> = new Map(
  KNOWLEDGE.filter((e): e is KnowledgeEntry & { topic: string } => e.topic != null).map(
    (e) => [e.topic.toLowerCase(), e],
  ),
)

export function getKnowledgeByNoradId(id: number): KnowledgeEntry | null {
  return NORAD_INDEX.get(id) ?? null
}

export function getKnowledgeByTopic(topic: string): KnowledgeEntry | null {
  return TOPIC_INDEX.get(topic.toLowerCase().trim()) ?? null
}
